session_name: kimera-distributed-jackal

environment:
  ROSBAG0: "/home/yunchang/Downloads/westpoint_husky_village_loop_1_2022-05-06-11-00-22.bag"
  ROSBAG1: "/home/yunchang/Downloads/westpoint_jackal_village_loop_4_2022-05-05-16-03-12.bag"
  ROBOT0: "chinook"
  ROBOT1: "sobek"
  RATE: "1.0"

options:
  default-command: /bin/bash

windows:
- window_name: robot-0
  layout: tiled  
  shell_command_before:
    - sleep 10;
    - source ~/catkin_ws/devel/setup.bash
    - export ROS_MASTER_URI=http://localhost:11311
    - rosparam set use_sim_time true

  panes:
    - roslaunch kimera_core kimera_vio_jackal.launch robot_name:=$ROBOT0 robot_id:=0 use_d455:=true multirobot:=true should_use_sim_time:=true lcd_no_optimize:=true use_external_odom:=false
    - roslaunch kimera_distributed kimera_distributed.launch robot_id:=0 robot_name:=$ROBOT0 num_robots:=2 dataset_name:=Jackal multi_master:=true
    - roslaunch kimera_distributed dpgo.launch robot_id:=0 robot_name:=$ROBOT0 num_robots:=2 dataset_name:=Jackal robot_names_config:=arl_robot_names
    - roslaunch kimera_semantics_ros kimera_semantics_jackal.launch robot_name:=$ROBOT0 decompress_depth:=false decompress_color:=false use_sim_time:=true left_cam_topic:=/$ROBOT0/forward/color/image_rect_color
    - roslaunch kimera_pgmo kimera_pgmo_robot.launch robot_name:=$ROBOT0 robot_id:=0 dataset:=Jackal run_mode:=1 optimized_path_topic:=/$ROBOT0/dpgo_ros_node/path pose_graph_topic:=/$ROBOT0/kimera_distributed/pose_graph_incremental
    - roslaunch object_mapper object_mapper_2.launch robot_name:=$ROBOT0
    - rviz -d $(rospack find kimera_distributed)/rviz/jackal_arl.rviz

- window_name: robot-1
  layout: tiled  
  shell_command_before:
    - sleep 10;
    - source ~/catkin_ws/devel/setup.bash
    - export ROS_MASTER_URI=http://localhost:11312
    - rosparam set use_sim_time true

  panes:
    - roslaunch kimera_core kimera_vio_jackal.launch robot_name:=$ROBOT1 robot_id:=1 use_d455:=true multirobot:=true replay:=true should_use_sim_time:=true lcd_no_optimize:=true use_external_odom:=false
    - roslaunch kimera_distributed kimera_distributed.launch robot_id:=1 robot_name:=$ROBOT1 num_robots:=2 dataset_name:=Jackal multi_master:=true
    - roslaunch kimera_distributed dpgo.launch robot_id:=1 robot_name:=$ROBOT1 num_robots:=2 dataset_name:=Jackal robot_names_config:=arl_robot_names
    - roslaunch kimera_semantics_ros kimera_semantics_jackal.launch robot_name:=$ROBOT1 decompress_depth:=false decompress_color:=false use_sim_time:=true left_cam_topic:=/$ROBOT1/forward/color/image_rect_color
    - roslaunch kimera_pgmo kimera_pgmo_robot.launch robot_name:=$ROBOT1 robot_id:=1 dataset:=Jackal run_mode:=1 optimized_path_topic:=/$ROBOT1/dpgo_ros_node/path pose_graph_topic:=/$ROBOT1/kimera_distributed/pose_graph_incremental
    - roslaunch object_mapper object_mapper_2.launch robot_name:=$ROBOT1
    # - rviz -d $(rospack find kimera_distributed)/rviz/kimera_jackal2_mit.rviz

- window_name: data
  focus: true  
  layout: tiled  
  shell_command_before:
    - source ~/catkin_ws/devel/setup.bash

  panes:
    - roscore -p 11311
    - roscore -p 11312
    - sleep 15; export ROS_MASTER_URI=http://localhost:11311; rosbag play $ROSBAG0 --clock -r$RATE --pause --topics /$ROBOT0/forward/infra1/camera_info /$ROBOT0/forward/infra2/camera_info /$ROBOT0/forward/depth/camera_info /$ROBOT0/forward/color/camera_info /$ROBOT0/forward/infra1/image_rect_raw /$ROBOT0/forward/infra2/image_rect_raw /$ROBOT0/forward/depth/image_rect_raw /$ROBOT0/forward/color/image_rect_color /$ROBOT0/forward/imu /$ROBOT0/jackal_velocity_controller/odom /tf_static /tf_aggregate /$ROBOT0/lidar_points /$ROBOT0/detection_out_topic
    - sleep 15; export ROS_MASTER_URI=http://localhost:11312; rosbag play $ROSBAG1 --clock -r$RATE --pause --topics /$ROBOT1/forward/infra1/camera_info /$ROBOT1/forward/infra2/camera_info /$ROBOT1/forward/depth/camera_info /$ROBOT1/forward/color/camera_info /$ROBOT1/forward/infra1/image_rect_raw /$ROBOT1/forward/infra2/image_rect_raw /$ROBOT1/forward/depth/image_rect_raw /$ROBOT1/forward/color/image_rect_color /$ROBOT1/forward/imu /$ROBOT1/jackal_velocity_controller/odom /tf_static /tf_aggregate /$ROBOT1/lidar_points /$ROBOT1/detection_out_topic
    - sleep 15; export ROS_MASTER_URI=http://localhost:11311; rosrun static_transform_mux static_transform_mux
    - sleep 15; export ROS_MASTER_URI=http://localhost:11312; rosrun static_transform_mux static_transform_mux
    - sleep 10; export ROS_MASTER_URI=http://localhost:11311; rosrun tf2_ros static_transform_publisher 0 0 0 0 0 1 world $ROBOT0/map
    - sleep 10; export ROS_MASTER_URI=http://localhost:11312; rosrun tf2_ros static_transform_publisher 0 0 0 0 0 1 world $ROBOT1/map