session_name: kimera-distributed-jackal

environment:
  ROSBAG0: "/home/yunchang/Downloads/kimera_test_j1_2022-03-25-15-34-40.bag"
  ROSBAG1: "/home/yunchang/Downloads/kimera_test_j2_2022-03-25-15-33-56.bag"
  RATE: "1.0"

options:
  default-command: /bin/bash

windows:
- window_name: acl_jackal
  layout: tiled  
  shell_command_before:
    - sleep 10;
    - source ~/catkin_ws/devel/setup.bash
    - export ROS_MASTER_URI=http://localhost:11311
    - rosparam set use_sim_time true

  panes:
    - roslaunch kimera_vio_ros arl_jackal.launch robot_name:=acl_jackal robot_id:=0 use_d455:=false multirobot:=true replay:=true should_use_sim_time:=true
    - roslaunch kimera_distributed kimera_distributed.launch robot_id:=0 robot_name:=acl_jackal num_robots:=2 dataset_name:=Jackal multi_master:=true
    - roslaunch kimera_semantics_ros kimera_semantics_jackal.launch robot_name:=acl_jackal decompress_depth:=false decompress_color:=true use_sim_time:=true
    - roslaunch kimera_pgmo kimera_pgmo_robot.launch robot_name:=acl_jackal robot_id:=0 dataset:=Jackal run_mode:=1 optimized_path_topic:=/acl_jackal/dpgo_ros_node/path
    - rviz -d $(rospack find kimera_distributed)/rviz/kimera_jackal_mit.rviz

- window_name: acl_jackal2
  layout: tiled  
  shell_command_before:
    - sleep 10;
    - source ~/catkin_ws/devel/setup.bash
    - export ROS_MASTER_URI=http://localhost:11312
    - rosparam set use_sim_time true

  panes:
    - roslaunch kimera_vio_ros arl_jackal.launch robot_name:=acl_jackal2 robot_id:=1 use_d455:=false multirobot:=true replay:=true should_use_sim_time:=true
    - roslaunch kimera_distributed kimera_distributed.launch robot_id:=1 robot_name:=acl_jackal2 num_robots:=2 dataset_name:=Jackal multi_master:=true
    - roslaunch kimera_semantics_ros kimera_semantics_jackal.launch robot_name:=acl_jackal2 decompress_depth:=false decompress_color:=true use_sim_time:=true
    - roslaunch kimera_pgmo kimera_pgmo_robot.launch robot_name:=acl_jackal2 robot_id:=1 dataset:=Jackal run_mode:=1 optimized_path_topic:=/acl_jackal2/dpgo_ros_node/path

- window_name: data
  focus: true  
  layout: tiled  
  shell_command_before:
    - source ~/catkin_ws/devel/setup.bash

  panes:
    - roscore -p 11311
    - roscore -p 11312
    - sleep 15; export ROS_MASTER_URI=http://localhost:11311; rosbag play $ROSBAG0 --clock -r$RATE --pause
    - sleep 15; export ROS_MASTER_URI=http://localhost:11312; rosbag play $ROSBAG1 --clock -r$RATE --pause
    - sleep 15; export ROS_MASTER_URI=http://localhost:11311; rosrun static_transform_mux static_transform_mux
    - sleep 15; export ROS_MASTER_URI=http://localhost:11312; rosrun static_transform_mux static_transform_mux
    - sleep 10; export ROS_MASTER_URI=http://localhost:11311; rosrun tf2_ros static_transform_publisher 0 0 0 0 0 1 world acl_jackal/map
    - sleep 10; export ROS_MASTER_URI=http://localhost:11312; rosrun tf2_ros static_transform_publisher 0 0 0 0 0 1 world acl_jackal2/map